#upated by Jo@20180611 修复client节点authorized_keys文件被覆盖的问题
#hdfs-master和yarn-master是2个单节点,在集群中不会增加或者删除，需要把这2个节点的pub_key写到client节点的authorized_keys文件中。
[template]
src = "profile.tmpl"
dest = "/etc/profile" 
keys = ["/hosts/hdfs-master/","/hosts/yarn-master/"] 
reload_cmd = ""
 
 
